[[rules]]
description = "Generic API Key"
regex = '''(?i)(api[_-]?key\s*=\s*['"][a-zA-Z0-9]{32,}['"])'''
tags = ["apikey"]

[[rules]]
description = "Password"
regex = '''(?i)(password\s*=\s*['"][^'"]+['"])'''
tags = ["password"]
